name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import Creds
        uses: ./
        id: creds
        with:
          connect-server-url: ${{ secrets.CONNECT_SERVER_URL }}
          connect-server-token: ${{ secrets.CONNECT_SERVER_TOKEN }}
          export-env-vars: "true"
          secret-path: |
            infra-secrets-shared > 1password.github-action-test-secret > username | MY_TEST_USERNAME
            infra-secrets-shared > 1password.github-action-test-secret | SECRET_NAME
            infra-secrets-shared > 1password.github-action-test-secret
      - name: Test ENV Var Set
        run: |
          if [[ "$MY_TEST_USERNAME" != "THIS_IS_the_USERNAME" ]]; then exit 1; fi

